services:

  postgres:
    build:
      context: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=projx
    ports:
      - "5432:5432"
